# Verify that train_test_split produces the same splits with random_state specified, no matter how many arrays are present in the function call

In [1]:
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np

In [4]:
X1 = np.linspace(0,50)
X2 = np.linspace(0,50)

In [5]:
X1tr, X1te, X2tr, X2te = train_test_split(X1, X2, test_size=0.2, random_state=1)

In [6]:
X1tr

array([32.65306122, 39.79591837, 21.42857143, 36.73469388, 19.3877551 ,
       42.85714286, 50.        , 26.53061224, 22.44897959, 13.26530612,
       41.83673469, 17.34693878, 45.91836735, 24.48979592, 23.46938776,
        4.08163265, 33.67346939, 14.28571429, 30.6122449 , 10.20408163,
       28.57142857, 44.89795918, 34.69387755, 18.36734694, 20.40816327,
       25.51020408,  6.12244898,  7.14285714, 47.95918367,  1.02040816,
       16.32653061,  0.        , 15.30612245,  5.10204082, 11.2244898 ,
        9.18367347,  8.16326531, 12.24489796, 43.87755102, 37.75510204])

In [12]:
X1tr, X1te = train_test_split(X1, test_size=0.2, random_state=1)

In [8]:
X1tr

array([32.65306122, 39.79591837, 21.42857143, 36.73469388, 19.3877551 ,
       42.85714286, 50.        , 26.53061224, 22.44897959, 13.26530612,
       41.83673469, 17.34693878, 45.91836735, 24.48979592, 23.46938776,
        4.08163265, 33.67346939, 14.28571429, 30.6122449 , 10.20408163,
       28.57142857, 44.89795918, 34.69387755, 18.36734694, 20.40816327,
       25.51020408,  6.12244898,  7.14285714, 47.95918367,  1.02040816,
       16.32653061,  0.        , 15.30612245,  5.10204082, 11.2244898 ,
        9.18367347,  8.16326531, 12.24489796, 43.87755102, 37.75510204])

It's safe to call this function on the tagger inputs alone, without DeepCSV. This will decrease the stuff that needs to be loaded into memory when producing the scalers for the preprocessing, as only my own datasets need to be present during the splitting.

Also need to check if the behaviour is the same when the array to split has varying second dimension (e.g. originally, I split arrays of NUMJETS * 67 size, but to not get any problems when running with every file, to calculate the scalers I will run with arrays of size NUMJETS * 1, so per input).

In [19]:
X3 = np.column_stack((X1,X2))

In [20]:
X3tr, X3te = train_test_split(X3, test_size=0.2, random_state=1)

In [21]:
X3tr

array([[32.65306122, 32.65306122],
       [39.79591837, 39.79591837],
       [21.42857143, 21.42857143],
       [36.73469388, 36.73469388],
       [19.3877551 , 19.3877551 ],
       [42.85714286, 42.85714286],
       [50.        , 50.        ],
       [26.53061224, 26.53061224],
       [22.44897959, 22.44897959],
       [13.26530612, 13.26530612],
       [41.83673469, 41.83673469],
       [17.34693878, 17.34693878],
       [45.91836735, 45.91836735],
       [24.48979592, 24.48979592],
       [23.46938776, 23.46938776],
       [ 4.08163265,  4.08163265],
       [33.67346939, 33.67346939],
       [14.28571429, 14.28571429],
       [30.6122449 , 30.6122449 ],
       [10.20408163, 10.20408163],
       [28.57142857, 28.57142857],
       [44.89795918, 44.89795918],
       [34.69387755, 34.69387755],
       [18.36734694, 18.36734694],
       [20.40816327, 20.40816327],
       [25.51020408, 25.51020408],
       [ 6.12244898,  6.12244898],
       [ 7.14285714,  7.14285714],
       [47.95918367,

In [28]:
np.array_equal(X3tr[:,0],X1tr[:])

True

Good, it does not matter if train_test_split gets the full dataset or only one column, the splitting is the same.