In [ ]:
import numpy as np

In [29]:
!python eval_inputs.py 0 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[0, 0.01, 0.0003314119587752626], [0, 0.02, 0.0011549849039156476]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[0.         0.01       0.00033141]
  [0.         0.02       0.00115498]]]
Figure(1000x600)
eval_inputs.py:318: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[0, 0.01, 0.0003314119587752626], [0, 0.02, 0.0011549849039156476]], [[0, 0.01, 0.0003314119587752626], [0, 0.02, 0.0011549849039156476]]]
[[[0.         0.01       0.00033141]
  [0.         0.02       0.00115498]]

 [[0.         0.01       0.00033141]
  [0.         0.02       0.00115498]]]
eval_inputs.py:460: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid li

In [20]:
print(np.load('inputs/kl_div/input_0_Jet_eta_fgsm[0, 0.01, 0.02]_spec_range_13283070__ptetaflavloss_focalloss_gamma25.0_200.npy'))

[[[0.         0.01       0.00025564]
  [0.         0.02       0.00097858]]]


In [30]:
!python eval_inputs.py 1 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[1, 0.01, 0.000669960527631526], [1, 0.02, 0.0018055779076368017]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.

In [31]:
!python eval_inputs.py 2 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[2, 0.01, 6.803500573050088e-06], [2, 0.02, 1.438383047321781e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2

In [32]:
!python eval_inputs.py 3 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[3, 0.01, 0.0001247736294189678], [3, 0.02, 0.0005189488521506434]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.00000000e+00 1.00000000e-02 1.24773629e-04]
  [3.00000000e+00 2.00000000e-02 5.18948852e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[3, 0.01, 0.0001247736294189678], [3, 0.02, 0.0005189488521506434]], [[3, 0.01, 0.0001247736294189678], [3, 0.02, 0.0005189488521506434]]]
[[[3.00000000e+00 1.00000000e-02 1.24773629e-04]
  [3.00000000e+00 2.00000000e-02 5.18948852e-04]]

 [[3.00000000e+00 1.00000000e-02 1.24773629e-04]
  [3.00000000e+00 2.00000000e-02 5.18948852e-04]]]
eval_inputs.py:458: UserWarning: At

In [33]:
!python eval_inputs.py 4 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[4, 0.01, 1.863341615041852e-05], [4, 0.02, 7.56324177542645e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.

In [34]:
!python eval_inputs.py 5 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[5, 0.01, 2.225342735077136e-05], [5, 0.02, 6.764553174338521e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5

In [35]:
!python eval_inputs.py 6 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[6, 0.01, 0.006250367259272146], [6, 0.02, 0.031427043025621264]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[6.         0.01       0.00625037]
  [6.         0.02       0.03142704]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[6, 0.01, 0.006250367259272146], [6, 0.02, 0.031427043025621264]], [[6, 0.01, 0.006250367259272146], [6, 0.02, 0.031427043025621264]]]
[[[6.         0.01       0.00625037]
  [6.         0.02       0.03142704]]

 [[6.         0.01       0.00625037]
  [6.         0.02       0.03142704]]]
eval_inputs.py:458: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit wi

In [36]:
!python eval_inputs.py 7 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[7, 0.01, 0.0018773010199622095], [7, 0.02, 0.008592595797628645]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[7.00000000e+00 1.00000000e-02 1.87730102e-03]
  [7.00000000e+00 2.00000000e-02 8.59259580e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[7, 0.01, 0.0018773010199622095], [7, 0.02, 0.008592595797628645]], [[7, 0.01, 0.0018773010199622095], [7, 0.02, 0.008592595797628645]]]
[[[7.00000000e+00 1.00000000e-02 1.87730102e-03]
  [7.00000000e+00 2.00000000e-02 8.59259580e-03]]

 [[7.00000000e+00 1.00000000e-02 1.87730102e-03]
  [7.00000000e+00 2.00000000e-02 8.59259580e-03]]]
eval_inputs.py:458: UserWarning: Attem

In [37]:
!python eval_inputs.py 8 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[8, 0.01, 0.0008853380713797728], [8, 0.02, 0.003987354877081124]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[8.00000000e+00 1.00000000e-02 8.85338071e-04]
  [8.00000000e+00 2.00000000e-02 3.98735488e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[8, 0.01, 0.0008853380713797728], [8, 0.02, 0.003987354877081124]], [[8, 0.01, 0.0008853380713797728], [8, 0.02, 0.003987354877081124]]]
[[[8.00000000e+00 1.00000000e-02 8.85338071e-04]
  [8.00000000e+00 2.00000000e-02 3.98735488e-03]]

 [[8.00000000e+00 1.00000000e-02 8.85338071e-04]
  [8.00000000e+00 2.00000000e-02 3.98735488e-03]]]
eval_inputs.py:458: UserWarning: Attem

In [38]:
!python eval_inputs.py 9 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[9, 0.01, 0.00037603289633402734], [9, 0.02, 0.0016594933078300617]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[9.00000000e+00 1.00000000e-02 3.76032896e-04]
  [9.00000000e+00 2.00000000e-02 1.65949331e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[9, 0.01, 0.00037603289633402734], [9, 0.02, 0.0016594933078300617]], [[9, 0.01, 0.00037603289633402734], [9, 0.02, 0.0016594933078300617]]]
[[[9.00000000e+00 1.00000000e-02 3.76032896e-04]
  [9.00000000e+00 2.00000000e-02 1.65949331e-03]]

 [[9.00000000e+00 1.00000000e-02 3.76032896e-04]
  [9.00000000e+00 2.00000000e-02 1.65949331e-03]]]
eval_inputs.py:458: UserWarning:

In [39]:
!python eval_inputs.py 10 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[10, 0.01, 0.0005106635193126708], [10, 0.02, 0.0022040622486303686]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.00000000e+01 1.00000000e-02 5.10663519e-04]
  [1.00000000e+01 2.00000000e-02 2.20406225e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[10, 0.01, 0.0005106635193126708], [10, 0.02, 0.0022040622486303686]], [[10, 0.01, 0.0005106635193126708], [10, 0.02, 0.0022040622486303686]]]
[[[1.00000000e+01 1.00000000e-02 5.10663519e-04]
  [1.00000000e+01 2.00000000e-02 2.20406225e-03]]

 [[1.00000000e+01 1.00000000e-02 5.10663519e-04]
  [1.00000000e+01 2.00000000e-02 2.20406225e-03]]]
eval_inputs.py:458: UserWarni

In [40]:
!python eval_inputs.py 11 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[11, 0.01, 0.00032101383184009375], [11, 0.02, 0.0014027305002364625]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.10000000e+01 1.00000000e-02 3.21013832e-04]
  [1.10000000e+01 2.00000000e-02 1.40273050e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[11, 0.01, 0.00032101383184009375], [11, 0.02, 0.0014027305002364625]], [[11, 0.01, 0.00032101383184009375], [11, 0.02, 0.0014027305002364625]]]
[[[1.10000000e+01 1.00000000e-02 3.21013832e-04]
  [1.10000000e+01 2.00000000e-02 1.40273050e-03]]

 [[1.10000000e+01 1.00000000e-02 3.21013832e-04]
  [1.10000000e+01 2.00000000e-02 1.40273050e-03]]]
eval_inputs.py:458: UserWa

In [41]:
!python eval_inputs.py 12 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[12, 0.01, 0.0003370876921456794], [12, 0.02, 0.00048304865518889037]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.20000000e+01 1.00000000e-02 3.37087692e-04]
  [1.20000000e+01 2.00000000e-02 4.83048655e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[12, 0.01, 0.0003370876921456794], [12, 0.02, 0.00048304865518889037]], [[12, 0.01, 0.0003370876921456794], [12, 0.02, 0.00048304865518889037]]]
[[[1.20000000e+01 1.00000000e-02 3.37087692e-04]
  [1.20000000e+01 2.00000000e-02 4.83048655e-04]]

 [[1.20000000e+01 1.00000000e-02 3.37087692e-04]
  [1.20000000e+01 2.00000000e-02 4.83048655e-04]]]
eval_inputs.py:458: UserWa

In [42]:
!python eval_inputs.py 13 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[13, 0.01, 0.000321544492403903], [13, 0.02, 0.000992844458090314]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.30000000e+01 1.00000000e-02 3.21544492e-04]
  [1.30000000e+01 2.00000000e-02 9.92844458e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[13, 0.01, 0.000321544492403903], [13, 0.02, 0.000992844458090314]], [[13, 0.01, 0.000321544492403903], [13, 0.02, 0.000992844458090314]]]
[[[1.30000000e+01 1.00000000e-02 3.21544492e-04]
  [1.30000000e+01 2.00000000e-02 9.92844458e-04]]

 [[1.30000000e+01 1.00000000e-02 3.21544492e-04]
  [1.30000000e+01 2.00000000e-02 9.92844458e-04]]]
eval_inputs.py:458: UserWarning: At

In [43]:
!python eval_inputs.py 14 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[14, 0.01, 0.00044096328399503663], [14, 0.02, 0.0006788591800195463]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.40000000e+01 1.00000000e-02 4.40963284e-04]
  [1.40000000e+01 2.00000000e-02 6.78859180e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[14, 0.01, 0.00044096328399503663], [14, 0.02, 0.0006788591800195463]], [[14, 0.01, 0.00044096328399503663], [14, 0.02, 0.0006788591800195463]]]
[[[1.40000000e+01 1.00000000e-02 4.40963284e-04]
  [1.40000000e+01 2.00000000e-02 6.78859180e-04]]

 [[1.40000000e+01 1.00000000e-02 4.40963284e-04]
  [1.40000000e+01 2.00000000e-02 6.78859180e-04]]]
eval_inputs.py:458: UserWa

In [44]:
!python eval_inputs.py 15 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[15, 0.01, 0.00020814429460495637], [15, 0.02, 0.00024056464203694436]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.50000000e+01 1.00000000e-02 2.08144295e-04]
  [1.50000000e+01 2.00000000e-02 2.40564642e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[15, 0.01, 0.00020814429460495637], [15, 0.02, 0.00024056464203694436]], [[15, 0.01, 0.00020814429460495637], [15, 0.02, 0.00024056464203694436]]]
[[[1.50000000e+01 1.00000000e-02 2.08144295e-04]
  [1.50000000e+01 2.00000000e-02 2.40564642e-04]]

 [[1.50000000e+01 1.00000000e-02 2.08144295e-04]
  [1.50000000e+01 2.00000000e-02 2.40564642e-04]]]
eval_inputs.py:458: Use

In [45]:
!python eval_inputs.py 16 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[16, 0.01, 0.00022442592805054927], [16, 0.02, 0.0003664024020763535]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.60000000e+01 1.00000000e-02 2.24425928e-04]
  [1.60000000e+01 2.00000000e-02 3.66402402e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[16, 0.01, 0.00022442592805054927], [16, 0.02, 0.0003664024020763535]], [[16, 0.01, 0.00022442592805054927], [16, 0.02, 0.0003664024020763535]]]
[[[1.60000000e+01 1.00000000e-02 2.24425928e-04]
  [1.60000000e+01 2.00000000e-02 3.66402402e-04]]

 [[1.60000000e+01 1.00000000e-02 2.24425928e-04]
  [1.60000000e+01 2.00000000e-02 3.66402402e-04]]]
eval_inputs.py:458: UserWa

In [46]:
!python eval_inputs.py 17 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[17, 0.01, 0.00010299855636645294], [17, 0.02, 0.0002150237963049269]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[1.70000000e+01 1.00000000e-02 1.02998556e-04]
  [1.70000000e+01 2.00000000e-02 2.15023796e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[17, 0.01, 0.00010299855636645294], [17, 0.02, 0.0002150237963049269]], [[17, 0.01, 0.00010299855636645294], [17, 0.02, 0.0002150237963049269]]]
[[[1.70000000e+01 1.00000000e-02 1.02998556e-04]
  [1.70000000e+01 2.00000000e-02 2.15023796e-04]]

 [[1.70000000e+01 1.00000000e-02 1.02998556e-04]
  [1.70000000e+01 2.00000000e-02 2.15023796e-04]]]
eval_inputs.py:458: UserWa

In [47]:
!python eval_inputs.py 18 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[18, 0.01, 0.0001332163962244383], [18, 0.02, 0.0005592792035286616]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[

In [48]:
!python eval_inputs.py 19 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[19, 0.01, 0.0001662532215995043], [19, 0.02, 0.0005062491528027895]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[

In [49]:
!python eval_inputs.py 20 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[20, 0.01, 3.0312715883045115e-05], [20, 0.02, 3.623688539243115e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[

In [50]:
!python eval_inputs.py 21 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[21, 0.01, 2.3790036207321037e-05], [21, 0.02, 2.1670374176685405e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.


In [51]:
!python eval_inputs.py 22 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[22, 0.01, 0.0012025597523393824], [22, 0.02, 0.004727571880879074]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.20000000e+01 1.00000000e-02 1.20255975e-03]
  [2.20000000e+01 2.00000000e-02 4.72757188e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[22, 0.01, 0.0012025597523393824], [22, 0.02, 0.004727571880879074]], [[22, 0.01, 0.0012025597523393824], [22, 0.02, 0.004727571880879074]]]
[[[2.20000000e+01 1.00000000e-02 1.20255975e-03]
  [2.20000000e+01 2.00000000e-02 4.72757188e-03]]

 [[2.20000000e+01 1.00000000e-02 1.20255975e-03]
  [2.20000000e+01 2.00000000e-02 4.72757188e-03]]]
eval_inputs.py:458: UserWarning:

In [52]:
!python eval_inputs.py 23 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[23, 0.01, 0.02292151846244557], [23, 0.02, 0.06426217382430711]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.30000000e+01 1.00000000e-02 2.29215185e-02]
  [2.30000000e+01 2.00000000e-02 6.42621738e-02]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[23, 0.01, 0.02292151846244557], [23, 0.02, 0.06426217382430711]], [[23, 0.01, 0.02292151846244557], [23, 0.02, 0.06426217382430711]]]
[[[2.30000000e+01 1.00000000e-02 2.29215185e-02]
  [2.30000000e+01 2.00000000e-02 6.42621738e-02]]

 [[2.30000000e+01 1.00000000e-02 2.29215185e-02]
  [2.30000000e+01 2.00000000e-02 6.42621738e-02]]]
eval_inputs.py:458: UserWarning: Attempte

In [53]:
!python eval_inputs.py 24 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[24, 0.01, 0.07084641007122905], [24, 0.02, 0.10185136453689711]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.40000000e+01 1.00000000e-02 7.08464101e-02]
  [2.40000000e+01 2.00000000e-02 1.01851365e-01]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[24, 0.01, 0.07084641007122905], [24, 0.02, 0.10185136453689711]], [[24, 0.01, 0.07084641007122905], [24, 0.02, 0.10185136453689711]]]
[[[2.40000000e+01 1.00000000e-02 7.08464101e-02]
  [2.40000000e+01 2.00000000e-02 1.01851365e-01]]

 [[2.40000000e+01 1.00000000e-02 7.08464101e-02]
  [2.40000000e+01 2.00000000e-02 1.01851365e-01]]]
eval_inputs.py:458: UserWarning: Attempte

In [54]:
!python eval_inputs.py 25 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[25, 0.01, 0.03191338685583825], [25, 0.02, 0.1373489850582498]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.50000000e+01 1.00000000e-02 3.19133869e-02]
  [2.50000000e+01 2.00000000e-02 1.37348985e-01]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[25, 0.01, 0.03191338685583825], [25, 0.02, 0.1373489850582498]], [[25, 0.01, 0.03191338685583825], [25, 0.02, 0.1373489850582498]]]
[[[2.50000000e+01 1.00000000e-02 3.19133869e-02]
  [2.50000000e+01 2.00000000e-02 1.37348985e-01]]

 [[2.50000000e+01 1.00000000e-02 3.19133869e-02]
  [2.50000000e+01 2.00000000e-02 1.37348985e-01]]]
eval_inputs.py:458: UserWarning: Attempted t

In [55]:
!python eval_inputs.py 26 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[26, 0.01, 0.017446571394904863], [26, 0.02, 0.13425725969897606]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.60000000e+01 1.00000000e-02 1.74465714e-02]
  [2.60000000e+01 2.00000000e-02 1.34257260e-01]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[26, 0.01, 0.017446571394904863], [26, 0.02, 0.13425725969897606]], [[26, 0.01, 0.017446571394904863], [26, 0.02, 0.13425725969897606]]]
[[[2.60000000e+01 1.00000000e-02 1.74465714e-02]
  [2.60000000e+01 2.00000000e-02 1.34257260e-01]]

 [[2.60000000e+01 1.00000000e-02 1.74465714e-02]
  [2.60000000e+01 2.00000000e-02 1.34257260e-01]]]
eval_inputs.py:458: UserWarning: Attem

In [56]:
!python eval_inputs.py 27 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[27, 0.01, 0.007812266538008268], [27, 0.02, 0.05039716109285462]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.70000000e+01 1.00000000e-02 7.81226654e-03]
  [2.70000000e+01 2.00000000e-02 5.03971611e-02]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[27, 0.01, 0.007812266538008268], [27, 0.02, 0.05039716109285462]], [[27, 0.01, 0.007812266538008268], [27, 0.02, 0.05039716109285462]]]
[[[2.70000000e+01 1.00000000e-02 7.81226654e-03]
  [2.70000000e+01 2.00000000e-02 5.03971611e-02]]

 [[2.70000000e+01 1.00000000e-02 7.81226654e-03]
  [2.70000000e+01 2.00000000e-02 5.03971611e-02]]]
eval_inputs.py:458: UserWarning: Attem

In [57]:
!python eval_inputs.py 28 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[28, 0.01, 0.0007349313125611382], [28, 0.02, 0.0010699475659020114]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.80000000e+01 1.00000000e-02 7.34931313e-04]
  [2.80000000e+01 2.00000000e-02 1.06994757e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: Runtime

In [58]:
!python eval_inputs.py 29 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[29, 0.01, 0.00024121349304902025], [29, 0.02, 0.0006604522586054066]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[2.90000000e+01 1.00000000e-02 2.41213493e-04]
  [2.90000000e+01 2.00000000e-02 6.60452259e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[29, 0.01, 0.00024121349304902025], [29, 0.02, 0.0006604522586054066]], [[29, 0.01, 0.00024121349304902025], [29, 0.02, 0.0006604522586054066]]]
[[[2.90000000e+01 1.00000000e-02 2.41213493e-04]
  [2.90000000e+01 2.00000000e-02 6.60452259e-04]]

 [[2.90000000e+01 1.00000000e-02 2.41213493e-04]
  [2.90000000e+01 2.00000000e-02 6.60452259e-04]]]
eval_inputs.py:458: UserWa

In [59]:
!python eval_inputs.py 30 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[30, 0.01, 0.000261948993429408], [30, 0.02, 0.0009489967717200036]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.00000000e+01 1.00000000e-02 2.61948993e-04]
  [3.00000000e+01 2.00000000e-02 9.48996772e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[30, 0.01, 0.000261948993429408], [30, 0.02, 0.0009489967717200036]], [[30, 0.01, 0.000261948993429408], [30, 0.02, 0.0009489967717200036]]]
[[[3.00000000e+01 1.00000000e-02 2.61948993e-04]
  [3.00000000e+01 2.00000000e-02 9.48996772e-04]]

 [[3.00000000e+01 1.00000000e-02 2.61948993e-04]
  [3.00000000e+01 2.00000000e-02 9.48996772e-04]]]
eval_inputs.py:458: UserWarning:

In [60]:
!python eval_inputs.py 31 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[31, 0.01, 0.00014859539296106845], [31, 0.02, 0.000298243369216374]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.10000000e+01 1.00000000e-02 1.48595393e-04]
  [3.10000000e+01 2.00000000e-02 2.98243369e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[31, 0.01, 0.00014859539296106845], [31, 0.02, 0.000298243369216374]], [[31, 0.01, 0.00014859539296106845], [31, 0.02, 0.000298243369216374]]]
[[[3.10000000e+01 1.00000000e-02 1.48595393e-04]
  [3.10000000e+01 2.00000000e-02 2.98243369e-04]]

 [[3.10000000e+01 1.00000000e-02 1.48595393e-04]
  [3.10000000e+01 2.00000000e-02 2.98243369e-04]]]
eval_inputs.py:458: UserWarni

In [61]:
!python eval_inputs.py 32 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[32, 0.01, 0.0001398775507889266], [32, 0.02, 0.0004114944996801018]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.20000000e+01 1.00000000e-02 1.39877551e-04]
  [3.20000000e+01 2.00000000e-02 4.11494500e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[32, 0.01, 0.0001398775507889266], [32, 0.02, 0.0004114944996801018]], [[32, 0.01, 0.0001398775507889266], [32, 0.02, 0.0004114944996801018]]]
[[[3.20000000e+01 1.00000000e-02 1.39877551e-04]
  [3.20000000e+01 2.00000000e-02 4.11494500e-04]]

 [[3.20000000e+01 1.00000000e-02 1.39877551e-04]
  [3.20000000e+01 2.00000000e-02 4.11494500e-04]]]
eval_inputs.py:458: UserWarni

In [62]:
!python eval_inputs.py 33 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[33, 0.01, 7.299741909561831e-05], [33, 0.02, 0.00011781785163177332]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.30000000e+01 1.00000000e-02 7.29974191e-05]
  [3.30000000e+01 2.00000000e-02 1.17817852e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[33, 0.01, 7.299741909561831e-05], [33, 0.02, 0.00011781785163177332]], [[33, 0.01, 7.299741909561831e-05], [33, 0.02, 0.00011781785163177332]]]
[[[3.30000000e+01 1.00000000e-02 7.29974191e-05]
  [3.30000000e+01 2.00000000e-02 1.17817852e-04]]

 [[3.30000000e+01 1.00000000e-02 7.29974191e-05]
  [3.30000000e+01 2.00000000e-02 1.17817852e-04]]]
eval_inputs.py:458: UserWa

In [63]:
!python eval_inputs.py 34 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[34, 0.01, 9.482251997465748e-05], [34, 0.02, 9.972628516163884e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.40000000e+01 1.00000000e-02 9.48225200e-05]
  [3.40000000e+01 2.00000000e-02 9.97262852e-05]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[34, 0.01, 9.482251997465748e-05], [34, 0.02, 9.972628516163884e-05]], [[34, 0.01, 9.482251997465748e-05], [34, 0.02, 9.972628516163884e-05]]]
[[[3.40000000e+01 1.00000000e-02 9.48225200e-05]
  [3.40000000e+01 2.00000000e-02 9.97262852e-05]]

 [[3.40000000e+01 1.00000000e-02 9.48225200e-05]
  [3.40000000e+01 2.00000000e-02 9.97262852e-05]]]
eval_inputs.py:458: UserWarni

In [64]:
!python eval_inputs.py 35 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[35, 0.01, 0.00012306476519826585], [35, 0.02, 0.0004996937264687626]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.50000000e+01 1.00000000e-02 1.23064765e-04]
  [3.50000000e+01 2.00000000e-02 4.99693726e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: Runtim

In [65]:
!python eval_inputs.py 36 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[36, 0.01, 7.073740891137771e-05], [36, 0.02, 0.00026067840700815637]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.60000000e+01 1.00000000e-02 7.07374089e-05]
  [3.60000000e+01 2.00000000e-02 2.60678407e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: Runtim

In [66]:
!python eval_inputs.py 37 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[37, 0.01, 6.413338725763489e-05], [37, 0.02, 0.00026863376099071424]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.70000000e+01 1.00000000e-02 6.41333873e-05]
  [3.70000000e+01 2.00000000e-02 2.68633761e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: Runtim

In [67]:
!python eval_inputs.py 38 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[38, 0.01, 2.378099393389411e-05], [38, 0.02, 9.662588768759363e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.80000000e+01 1.00000000e-02 2.37809939e-05]
  [3.80000000e+01 2.00000000e-02 9.66258877e-05]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: Runtime

In [68]:
!python eval_inputs.py 39 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[39, 0.01, 2.1221663883910823e-05], [39, 0.02, 7.964698860959615e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[3.90000000e+01 1.00000000e-02 2.12216639e-05]
  [3.90000000e+01 2.00000000e-02 7.96469886e-05]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: Runtim

In [69]:
!python eval_inputs.py 40 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[40, 0.01, 2.3236650543547602e-05], [40, 0.02, 6.1255234287477e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[

In [70]:
!python eval_inputs.py 41 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[41, 0.01, 0.007076641579661125], [41, 0.02, 0.4602853779749684]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.1

In [71]:
!python eval_inputs.py 42 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[42, 0.01, 0.00012182061939074087], [42, 0.02, 0.0006345638270140522]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.20000000e+01 1.00000000e-02 1.21820619e-04]
  [4.20000000e+01 2.00000000e-02 6.34563827e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: Runtim

In [72]:
!python eval_inputs.py 43 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[43, 0.01, 0.003799559048731365], [43, 0.02, 0.021712458655069003]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4

In [73]:
!python eval_inputs.py 44 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[44, 0.01, 0.035431776961684716], [44, 0.02, 0.14312110332324787]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.

In [74]:
!python eval_inputs.py 45 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[45, 0.01, 0.040107960719746025], [45, 0.02, 0.2046374631971282]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.5

In [75]:
!python eval_inputs.py 46 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[46, 0.01, 0.03449505141461186], [46, 0.02, 0.12237276991985992]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.6

In [76]:
!python eval_inputs.py 47 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[47, 0.01, 0.9987646360766856], [47, 0.02, 1.0557750423645602]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.700

In [77]:
!python eval_inputs.py 48 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[48, 0.01, 0.043529431574683704], [48, 0.02, 0.8621636457149652]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.8

In [78]:
!python eval_inputs.py 49 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[49, 0.01, 0.06548983904612701], [49, 0.02, 0.09731538395215317]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[4.9

In [79]:
!python eval_inputs.py 50 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[50, 0.01, 0.0002791768139389594], [50, 0.02, 0.0004610788040592825]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[

In [80]:
!python eval_inputs.py 51 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[51, 0.01, 0.27750320375686766], [51, 0.02, 0.2793904653435914]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5.10

In [81]:
!python eval_inputs.py 52 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[52, 0.01, 0.0032954983096653034], [52, 0.02, 0.007031446637868568]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[

In [82]:
!python eval_inputs.py 53 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[53, 0.01, 0.05729172023893286], [53, 0.02, 0.2765884046641123]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5.30

In [83]:
!python eval_inputs.py 54 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[54, 0.01, 0.004130484815348044], [54, 0.02, 0.05155349271597818]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5.

In [84]:
!python eval_inputs.py 55 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[55, 0.01, 0.006626461538308382], [55, 0.02, 1.8865291730549776]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5.5

In [85]:
!python eval_inputs.py 56 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[56, 0.01, 0.2690462336360232], [56, 0.02, 1.3222694232996168]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5.600

In [86]:
!python eval_inputs.py 57 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[57, 0.01, 0.00033590813355182996], [57, 0.02, 0.0010182606470345542]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5.70000000e+01 1.00000000e-02 3.35908134e-04]
  [5.70000000e+01 2.00000000e-02 1.01826065e-03]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[57, 0.01, 0.00033590813355182996], [57, 0.02, 0.0010182606470345542]], [[57, 0.01, 0.00033590813355182996], [57, 0.02, 0.0010182606470345542]]]
[[[5.70000000e+01 1.00000000e-02 3.35908134e-04]
  [5.70000000e+01 2.00000000e-02 1.01826065e-03]]

 [[5.70000000e+01 1.00000000e-02 3.35908134e-04]
  [5.70000000e+01 2.00000000e-02 1.01826065e-03]]]
eval_inputs.py:458: UserWa

In [87]:
!python eval_inputs.py 58 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[58, 0.01, 8.593386878856747e-05], [58, 0.02, 0.0003236804304254336]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[

In [88]:
!python eval_inputs.py 59 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[59, 0.01, 0.0], [59, 0.02, 0.0]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[5.9e+01 1.0e-02 0.0e+00]
  [5.9e+01 2.0e-02 0.0e+00]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_e

In [89]:
!python eval_inputs.py 60 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[60, 0.01, 7.719607770968395e-08], [60, 0.02, 1.23105831394761e-07]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[6.00000000e+01 1.00000000e-02 7.71960777e-08]
  [6.00000000e+01 2.00000000e-02 1.23105831e-07]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: RuntimeW

In [90]:
!python eval_inputs.py 61 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
[[[61, 0.01, 0.00012491998722009986], [61, 0.02, 0.00015390625008946236]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[6.10000000e+01 1.00000000e-02 1.24919987e-04]
  [6.10000000e+01 2.00000000e-02 1.53906250e-04]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
[[[61, 0.01, 0.00012491998722009986], [61, 0.02, 0.00015390625008946236]], [[61, 0.01, 0.00012491998722009986], [61, 0.02, 0.00015390625008946236]]]
[[[6.10000000e+01 1.00000000e-02 1.24919987e-04]
  [6.10000000e+01 2.00000000e-02 1.53906250e-04]]

 [[6.10000000e+01 1.00000000e-02 1.24919987e-04]
  [6.10000000e+01 2.00000000e-02 1.53906250e-04]]]
eval_inputs.py:458: Use

In [91]:
!python eval_inputs.py 62 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: divide by zero encountered in true_divide
  ratio = num / denom
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: divide by zero encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
eval_inputs.py:262: RuntimeWarning: invalid value encountered in multiply
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[62, 0.01, 8.630260471098175e-06], [62, 0.02, 1.1495428364146144e-05]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[

In [92]:
!python eval_inputs.py 63 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[63, 0.01, 0.0], [63, 0.02, 0.0]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[6.3e+01 1.0e-02 0.0e+00]
  [6.3e+01 2.0e-02 0.0e+00]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_e

In [93]:
!python eval_inputs.py 64 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[64, 0.01, 0.0], [64, 0.02, 0.0]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[6.4e+01 1.0e-02 0.0e+00]
  [6.4e+01 2.0e-02 0.0e+00]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_e

In [94]:
!python eval_inputs.py 65 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[65, 0.01, 0.0], [65, 0.02, 0.0]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[6.5e+01 1.0e-02 0.0e+00]
  [6.5e+01 2.0e-02 0.0e+00]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_e

In [95]:
!python eval_inputs.py 66 fgsm yes '0.01,0.02' 278 200 _ptetaflavloss_focalloss_gamma25.0 0.001 -1 yes

Evaluate training at epoch 200
With weighting method _ptetaflavloss_focalloss_gamma25.0
gamma ['25.0']
alpha ['25.0']
epsilon ['_ptetaflavloss_focalloss_gamma25.0']
Loaded model and corresponding criterion.
eval_inputs.py:259: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:262: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_err/denom)**2+(num/(denom**2)*denom_err)**2)
[[[66, 0.01, 0.0], [66, 0.02, 0.0]]]
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
[[[6.6e+01 1.0e-02 0.0e+00]
  [6.6e+01 2.0e-02 0.0e+00]]]
Figure(1000x600)
eval_inputs.py:316: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  ax1.set_ylim(None, None)
eval_inputs.py:330: RuntimeWarning: invalid value encountered in true_divide
  ratio = num / denom
eval_inputs.py:333: RuntimeWarning: invalid value encountered in true_divide
  ratio_err = np.sqrt((num_e